<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $vehicles = [
            [
                'name'                 => 'Toyota Corolla 2021',
                'brand'                => 'Toyota',
                'model'                => 'Corolla',
                'category'             => 'Berline',
                'year'                 => 2021,
                'license_plate'        => 'BJ-1234-A',
                'seats'                => 5,
                'fuel_type'            => 'essence',
                'transmission'         => 'automatique',
                'description'          => 'La Toyota Corolla 2021 est une berline fiable et confortable, idéale pour vos déplacements quotidiens à Cotonou et dans tout le Bénin. Climatisation, GPS intégré, sièges confortables et faible consommation de carburant.',
                'photo'                => 'toyota-corolla.jpg',
                'status'               => 'disponible',
                'price_without_driver' => 25000,
                'price_with_driver'    => 40000,
            ],
            [
                'name'                 => 'Toyota Hilux 2022',
                'brand'                => 'Toyota',
                'model'                => 'Hilux',
                'category'             => 'Pick-up',
                'year'                 => 2022,
                'license_plate'        => 'BJ-5678-B',
                'seats'                => 5,
                'fuel_type'            => 'diesel',
                'transmission'         => 'manuelle',
                'description'          => 'Le Toyota Hilux 2022 est un pick-up robuste et polyvalent, parfait pour les terrains difficiles et les zones rurales du Bénin. Capacité de charge élevée, 4x4 intégral, idéal pour les missions en brousse ou les événements.',
                'photo'                => 'toyota-hilux.jpg',
                'status'               => 'disponible',
                'price_without_driver' => 35000,
                'price_with_driver'    => 50000,
            ],
            [
                'name'                 => 'Toyota Land Cruiser 2020',
                'brand'                => 'Toyota',
                'model'                => 'Land Cruiser',
                'category'             => '4x4',
                'year'                 => 2020,
                'license_plate'        => 'BJ-9012-C',
                'seats'                => 7,
                'fuel_type'            => 'diesel',
                'transmission'         => 'automatique',
                'description'          => 'Le Toyota Land Cruiser est le 4x4 de référence pour les terrains les plus exigeants. Spacieux avec 7 places, tout-terrain performant, climatisation, parfait pour les familles ou les groupes en voyage touristique au Bénin.',
                'photo'                => 'toyota-land-cruiser.jpg',
                'status'               => 'disponible',
                'price_without_driver' => 55000,
                'price_with_driver'    => 75000,
            ],
            [
                'name'                 => 'Mercedes-Benz C200 2021',
                'brand'                => 'Mercedes-Benz',
                'model'                => 'C200',
                'category'             => 'Luxe',
                'year'                 => 2021,
                'license_plate'        => 'BJ-3456-D',
                'seats'                => 5,
                'fuel_type'            => 'essence',
                'transmission'         => 'automatique',
                'description'          => 'La Mercedes-Benz C200 offre une expérience de conduite de luxe incomparable. Intérieur cuir, système audio premium, conduite sportive et élégante. Le choix idéal pour vos événements d\'affaires, mariages et occasions spéciales à Cotonou.',
                'photo'                => 'mercedes-c200.jpg',
                'status'               => 'disponible',
                'price_without_driver' => 65000,
                'price_with_driver'    => 85000,
            ],
            [
                'name'                 => 'Hyundai Tucson 2022',
                'brand'                => 'Hyundai',
                'model'                => 'Tucson',
                'category'             => 'SUV',
                'year'                 => 2022,
                'license_plate'        => 'BJ-7890-E',
                'seats'                => 5,
                'fuel_type'            => 'essence',
                'transmission'         => 'automatique',
                'description'          => 'Le Hyundai Tucson 2022 est un SUV moderne et élégant, parfait pour la ville comme pour les longues distances. Équipé d\'une caméra de recul, d\'un écran tactile et d\'une excellente climatisation pour votre confort au Bénin.',
                'photo'                => 'hyundai-tucson.jpg',
                'status'               => 'disponible',
                'price_without_driver' => 40000,
                'price_with_driver'    => 58000,
            ],
            [
                'name'                 => 'Honda CR-V 2021',
                'brand'                => 'Honda',
                'model'                => 'CR-V',
                'category'             => 'SUV',
                'year'                 => 2021,
                'license_plate'        => 'BJ-2345-F',
                'seats'                => 5,
                'fuel_type'            => 'essence',
                'transmission'         => 'automatique',
                'description'          => 'Le Honda CR-V est un SUV compact reconnu pour sa fiabilité et son espace intérieur généreux. Coffre spacieux, consommation raisonnable et confort optimal pour vos déplacements professionnels ou familiaux au Bénin.',
                'photo'                => 'honda-crv.jpg',
                'status'               => 'disponible',
                'price_without_driver' => 38000,
                'price_with_driver'    => 55000,
            ],
            [
                'name'                 => 'Kia Sportage 2023',
                'brand'                => 'Kia',
                'model'                => 'Sportage',
                'category'             => 'SUV',
                'year'                 => 2023,
                'license_plate'        => 'BJ-6789-G',
                'seats'                => 5,
                'fuel_type'            => 'essence',
                'transmission'         => 'automatique',
                'description'          => 'Le tout nouveau Kia Sportage 2023 allie design moderne et technologie avancée. Tableau de bord panoramique, assistance à la conduite, connectivité Apple CarPlay et Android Auto. Le SUV le plus récent de notre flotte.',
                'photo'                => 'kia-sportage.jpg',
                'status'               => 'disponible',
                'price_without_driver' => 42000,
                'price_with_driver'    => 60000,
            ],
            [
                'name'                 => 'Nissan Patrol 2020',
                'brand'                => 'Nissan',
                'model'                => 'Patrol',
                'category'             => '4x4',
                'year'                 => 2020,
                'license_plate'        => 'BJ-0123-H',
                'seats'                => 7,
                'fuel_type'            => 'diesel',
                'transmission'         => 'automatique',
                'description'          => 'Le Nissan Patrol est un 4x4 légendaire, robuste et puissant. Idéal pour les missions longues distances, les excursions en brousse et les déplacements en groupes. 7 places confortables avec une motorisation diesel économique.',
                'photo'                => 'nissan-patrol.jpg',
                'status'               => 'reservee',
                'price_without_driver' => 60000,
                'price_with_driver'    => 80000,
            ],
            [
                'name'                 => 'BMW Série 3 2021',
                'brand'                => 'BMW',
                'model'                => 'Série 3',
                'category'             => 'Luxe',
                'year'                 => 2021,
                'license_plate'        => 'BJ-4567-I',
                'seats'                => 5,
                'fuel_type'            => 'essence',
                'transmission'         => 'automatique',
                'description'          => 'La BMW Série 3 incarne l\'excellence allemande. Sportive, élégante et puissante, elle est le choix parfait pour impressionner lors de vos réunions d\'affaires, cérémonies de mariage et événements de prestige à Cotonou.',
                'photo'                => 'bmw-serie3.jpg',
                'status'               => 'disponible',
                'price_without_driver' => 70000,
                'price_with_driver'    => 90000,
            ],
            [
                'name'                 => 'Toyota Prado 2022',
                'brand'                => 'Toyota',
                'model'                => 'Prado',
                'category'             => '4x4',
                'year'                 => 2022,
                'license_plate'        => 'BJ-8901-J',
                'seats'                => 7,
                'fuel_type'            => 'diesel',
                'transmission'         => 'automatique',
                'description'          => 'Le Toyota Prado 2022 est un SUV premium tout-terrain. Avec ses 7 places, sa suspension adaptative et ses équipements haut de gamme, il est parfait pour les voyages en famille ou les convois d\'entreprise sur toutes les routes du Bénin.',
                'photo'                => 'toyota-prado.jpg',
                'status'               => 'disponible',
                'price_without_driver' => 58000,
                'price_with_driver'    => 78000,
            ],
            [
                'name'                 => 'Mitsubishi Pajero 2020',
                'brand'                => 'Mitsubishi',
                'model'                => 'Pajero',
                'category'             => '4x4',
                'year'                 => 2020,
                'license_plate'        => 'BJ-2468-K',
                'seats'                => 7,
                'fuel_type'            => 'diesel',
                'transmission'         => 'manuelle',
                'description'          => 'Le Mitsubishi Pajero est un 4x4 polyvalent et endurant. Robuste sur les pistes comme sur l\'asphalte, il offre 7 places et une grande capacité de chargement. Parfait pour les missions humanitaires, les excursions et les longs voyages.',
                'photo'                => 'mitsubishi-pajero.jpg',
                'status'               => 'maintenance',
                'price_without_driver' => 45000,
                'price_with_driver'    => 63000,
            ],
            [
                'name'                 => 'Ford Ranger 2022',
                'brand'                => 'Ford',
                'model'                => 'Ranger',
                'category'             => 'Pick-up',
                'year'                 => 2022,
                'license_plate'        => 'BJ-1357-L',
                'seats'                => 5,
                'fuel_type'            => 'diesel',
                'transmission'         => 'automatique',
                'description'          => 'Le Ford Ranger 2022 est un pick-up double cabine moderne et puissant. Adapté aux terrains difficiles, il allie capacité de travail et confort passager. Idéal pour les chantiers, les transports de matériel et les déplacements en zones rurales au Bénin.',
                'photo'                => 'ford-ranger.jpg',
                'status'               => 'disponible',
                'price_without_driver' => 38000,
                'price_with_driver'    => 55000,
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::updateOrCreate(
                ['license_plate' => $vehicle['license_plate']],
                $vehicle
            );
        }

        $this->command->info('✅ ' . count($vehicles) . ' véhicules créés avec succès.');
    }
}
